const CONNECTOR_REPO_URL = 'https://github.com/skwarcank/AIFLows.git';

function shellSingleQuote(value: string): string {
  return `'${value.split("'").join("'\\''")}'`;
}

export function buildConnectorInstallScript(apiBaseUrl: string): string {
  const usage = `curl -fsSL ${apiBaseUrl}/api/connectors/install.sh | bash -s -- --token <pairing-token>`;

  return [
    '#!/usr/bin/env bash',
    'set -euo pipefail',
    '',
    `API_BASE_URL=${shellSingleQuote(apiBaseUrl)}`,
    `REPO_URL=${shellSingleQuote(CONNECTOR_REPO_URL)}`,
    'TOKEN=""',
    '',
    'while [[ $# -gt 0 ]]; do',
    '  case "$1" in',
    '    --token)',
    '      TOKEN="${2:-}"',
    '      shift 2',
    '      ;;',
    '    *)',
    '      echo "Unknown argument: $1" >&2',
    `      echo ${shellSingleQuote(`Usage: ${usage}`)} >&2`,
    '      exit 1',
    '      ;;',
    '  esac',
    'done',
    '',
    'if [[ -z "$TOKEN" ]]; then',
    '  echo "Missing pairing token." >&2',
    `  echo ${shellSingleQuote(`Usage: ${usage}`)} >&2`,
    '  exit 1',
    'fi',
    '',
    'for command in git node npm; do',
    '  if ! command -v "$command" >/dev/null 2>&1; then',
    '    echo "Missing required command: $command" >&2',
    '    echo "Install $command, then re-run the connector command from Hosted AIFlows." >&2',
    '    exit 1',
    '  fi',
    'done',
    '',
    'WORKDIR="${TMPDIR:-/tmp}/aiflows-connector-$$"',
    'rm -rf "$WORKDIR"',
    'mkdir -p "$WORKDIR"',
    '',
    'cleanup() {',
    '  rm -rf "$WORKDIR"',
    '}',
    'trap cleanup EXIT',
    '',
    'echo "Downloading AIFlows Connector..."',
    'git clone --depth 1 "$REPO_URL" "$WORKDIR/repo" >/dev/null 2>&1',
    'cd "$WORKDIR/repo"',
    '',
    'echo "Installing Connector dependencies..."',
    'npm install >/dev/null',
    '',
    'echo "Building Connector..."',
    'npm run build -w packages/connector >/dev/null',
    '',
    'echo "Pairing Connector with Hosted AIFlows..."',
    'node packages/connector/dist/cli.js connect --api-base-url "$API_BASE_URL" --token "$TOKEN"',
    '',
  ].join('\n');
}
