const CONNECTOR_REPO_URL = 'https://github.com/skwarcank/AIFLows.git';

function shellSingleQuote(value: string): string {
  return `'${value.split("'").join("'\\''")}'`;
}

export function buildConnectorInstallScript(apiBaseUrl: string): string {
  const usage = `curl -fsSL ${apiBaseUrl}/api/connectors/install.sh | bash -s -- --token <pairing-token>`;

  return [
    '#!/usr/bin/env bash',
    'set -euo pipefail',
    '',
    `API_BASE_URL=${shellSingleQuote(apiBaseUrl)}`,
    `REPO_URL=${shellSingleQuote(CONNECTOR_REPO_URL)}`,
    'TOKEN=""',
    '',
    'while [[ $# -gt 0 ]]; do',
    '  case "$1" in',
    '    --token)',
    '      TOKEN="${2:-}"',
    '      shift 2',
    '      ;;',
    '    *)',
    '      echo "Unknown argument: $1" >&2',
    `      echo ${shellSingleQuote(`Usage: ${usage}`)} >&2`,
    '      exit 1',
    '      ;;',
    '  esac',
    'done',
    '',
    'if [[ -z "$TOKEN" ]]; then',
    '  echo "Missing pairing token." >&2',
    `  echo ${shellSingleQuote(`Usage: ${usage}`)} >&2`,
    '  exit 1',
    'fi',
    '',
    'for command in git node npm; do',
    '  if ! command -v "$command" >/dev/null 2>&1; then',
    '    echo "Missing required command: $command" >&2',
    '    echo "Install $command, then re-run the connector command from Hosted AIFlows." >&2',
    '    exit 1',
    '  fi',
    'done',
    '',
    'INSTALL_DIR="$HOME/.aiflows/connector-src"',
    'BIN_DIR="$HOME/.aiflows/bin"',
    'BIN_PATH="$BIN_DIR/aiflows-connector"',
    'SHORT_BIN_PATH="$BIN_DIR/aiflows"',
    'if [[ -t 1 && -z "${NO_COLOR:-}" ]]; then',
    '  BOLD=$\'\\033[1m\'; UNDERLINE=$\'\\033[4m\'; GREEN=$\'\\033[32m\'; YELLOW=$\'\\033[33m\'; CYAN=$\'\\033[36m\'; RESET=$\'\\033[0m\'',
    'else',
    '  BOLD=""; UNDERLINE=""; GREEN=""; YELLOW=""; CYAN=""; RESET=""',
    'fi',
    'rm -rf "$INSTALL_DIR"',
    'mkdir -p "$INSTALL_DIR" "$BIN_DIR"',
    '',
    'echo "Downloading AIFlows Connector..."',
    'git clone --depth 1 "$REPO_URL" "$INSTALL_DIR" >/dev/null 2>&1',
    'cd "$INSTALL_DIR"',
    '',
    'echo "Installing Connector dependencies..."',
    'npm install >/dev/null',
    '',
    'echo "Building Connector..."',
    'npm run build -w packages/connector >/dev/null',
    '',
    "cat > \"$BIN_PATH\" <<'EOF'",
    '#!/usr/bin/env bash',
    'exec node "$HOME/.aiflows/connector-src/packages/connector/dist/cli.js" "$@"',
    'EOF',
    'chmod +x "$BIN_PATH"',
    'ln -sf "$BIN_PATH" "$SHORT_BIN_PATH"',
    '',
    'echo ""',
    'echo "${GREEN}✓ Installed AIFlows Connector${RESET}"',
    'echo ""',
    'echo "${BOLD}${UNDERLINE}Run anytime:${RESET}"',
    'echo "  ${CYAN}$BIN_PATH tldr${RESET}  # quick help"',
    'echo "  ${CYAN}$BIN_PATH run${RESET}   # start syncing"',
    'echo "  ${CYAN}$SHORT_BIN_PATH tldr${RESET}            # short alias"',
    'echo ""',
    'SHELL_RC=""',
    'if [[ -n "${ZSH_VERSION:-}" ]]; then SHELL_RC="$HOME/.zshrc"; elif [[ -n "${BASH_VERSION:-}" ]]; then SHELL_RC="$HOME/.bashrc"; fi',
    'if [[ -z "$SHELL_RC" ]]; then SHELL_RC="$HOME/.profile"; fi',
    'if [[ ":$PATH:" != *":$BIN_DIR:"* ]]; then',
    '  echo "${YELLOW}! PATH missing:${RESET} plain ${CYAN}aiflows-connector${RESET} will not work yet."',
    '  echo "Full path above always works."',
    '  echo ""',
    '  ADD_PATH=""',
    '  if [[ -r /dev/tty ]]; then',
    '    read -r -p "Add AIFlows to PATH in $SHELL_RC now? [y/N] " ADD_PATH < /dev/tty || ADD_PATH=""',
    '  else',
    '    echo "No interactive terminal available for PATH prompt."',
    '  fi',
    '  if [[ "$ADD_PATH" == "y" || "$ADD_PATH" == "Y" || "$ADD_PATH" == "yes" || "$ADD_PATH" == "YES" ]]; then',
    '    LINE=\'export PATH=$HOME/.aiflows/bin:$PATH\'',
    '    touch "$SHELL_RC"',
    '    if ! grep -F "$BIN_DIR" "$SHELL_RC" >/dev/null 2>&1; then',
    '      printf "\\n# AIFlows Connector\\n%s\\n" "$LINE" >> "$SHELL_RC"',
    '      echo "${GREEN}✓ PATH updated:${RESET} $SHELL_RC"',
    '    else',
    '      echo "${GREEN}✓ PATH already configured in:${RESET} $SHELL_RC"',
    '    fi',
    '    export PATH="$BIN_DIR:$PATH"',
    '    echo "New terminals: run ${CYAN}source $SHELL_RC${RESET} or restart shell."',
    '  else',
    '    echo "Manual later:"',
    "    echo \"  echo 'export PATH=\\$HOME/.aiflows/bin:\\$PATH' >> $SHELL_RC && source $SHELL_RC\"",
    '  fi',
    'else',
    '  echo "${GREEN}✓ PATH ready:${RESET} try ${CYAN}aiflows-connector tldr${RESET}"',
    'fi',
    '',
    'echo ""',
    'echo "${BOLD}Starting setup.${RESET} If you start watching, stop with ${YELLOW}Ctrl+C${RESET}; restart with:"',
    'echo "  ${CYAN}$BIN_PATH run${RESET}"',
    'echo ""',
    'if [[ -r /dev/tty ]]; then',
    '  "$BIN_PATH" setup --api-base-url "$API_BASE_URL" --token "$TOKEN" < /dev/tty',
    'else',
    '  echo "This installer needs an interactive terminal for guided setup." >&2',
    '  echo "Run manually: $BIN_PATH setup --api-base-url $API_BASE_URL --token <token>" >&2',
    '  exit 1',
    'fi',
    '',
  ].join('\n');
}
